SELECT * FROM TB_CUSTOMER;
SELECT CUSTOMER_CD, CUSTOMER_NM, PHONE_NUMBER, EMAIL FROM TB_CUSTOMER;

SELECT CUSTOMER_CD AS 코드, CUSTOMER_NM AS 고객명 FROM TB_CUSTOMER ORDER BY CUSTOMER_NM;

SELECT A.CUSTOMER_CD,
 A.CUSTOMER_NM,
 A.MW_FLG,
 B.POINT
FROM TB_CUSTOMER A,
 TB_POINT B
WHERE A.CUSTOMER_CD = '2017042'
AND A.CUSTOMER_CD = B.CUSTOMER_CD
AND B.POINT > 10000;

SELECT * FROM TB_POINT;
SELECT CUSTOMER_CD, POINT_MEMO, POINT FROM TB_POINT;
SELECT CUSTOMER_CD AS 고객코드, POINT_MEMO AS "포인트 내용", POINT AS 포인트 FROM TB_POINT;
-- 검색시 따옴표 한개 정의시 두개
SELECT * FROM TB_CUSTOMER WHERE CUSTOMER_NM = '김한길';
SELECT CUSTOMER_CD, CUSTOMER_NM, EMAIL, TOTAL_POINT FROM TB_CUSTOMER WHERE TOTAL_POINT < 10000;

SELECT CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY FROM TB_CUSTOMER WHERE 
    CUSTOMER_CD > '2019000' AND MW_FLG = 'W';
    
SELECT CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY FROM TB_CUSTOMER WHERE
    BIRTH_DAY < '19900000' AND MW_FLG = 'M';

SELECT CUSTOMER_CD, SEQ_NO, POINT FROM TB_POINT WHERE 
    CUSTOMER_CD = '2017053' AND SEQ_NO = 2;
-- OR
SELECT CUSTOMER_CD, MW_FLG, BIRTH_DAY, TOTAL_POINT FROM TB_CUSTOMER WHERE
    BIRTH_DAY >= '19900101' OR TOTAL_POINT >= 20000;
    
SELECT CUSTOMER_CD, MW_FLG, BIRTH_DAY, TOTAL_POINT FROM TB_CUSTOMER WHERE
    MW_FLG ='M' AND (BIRTH_DAY <= '19700101' OR TOTAL_POINT >= 20000);
    
-- GRADE 테이블
SELECT * FROM TB_GRADE WHERE (CLASS_CD = 'A' OR CLASS_CD ='B') 
    OR (KOR >=80 AND ENG >= 80 AND MAT >=80);

-- BETWEEN .. AND
SELECT * FROM TB_CUSTOMER WHERE BIRTH_DAY BETWEEN '19800101' AND '19891231';

SELECT * FROM TB_POINT WHERE REG_DTTM 
    BETWEEN '20180101000000' AND '20181231235959' AND POINT BETWEEN '10000' AND '50000';

SELECT CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, TOTAL_POINT FROM TB_CUSTOMER
    WHERE TOTAL_POINT >= 20000 AND MW_FLG = 'M' AND BIRTH_DAY >= '19800101'
    AND BIRTH_DAY <= '19892131';


-- LIKE    
SELECT * FROM TB_CUSTOMER WHERE CUSTOMER_CD LIKE '2018%';
SELECT * FROM TB_CUSTOMER WHERE PHONE_NUMBER NOT LIKE '___-____-____';

SELECT CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, TOTAL_POINT 
    FROM TB_CUSTOMER
    WHERE MW_FLG = 'M' 
    AND (BIRTH_DAY LIKE '____05%' OR BIRTH_DAY LIKE '____06%'
    OR BIRTH_DAY LIKE '____07%');
    
SELECT CUSTOMER_CD, CUSTOMER_NM, MW_FLG, BIRTH_DAY, TOTAL_POINT 
    FROM TB_CUSTOMER
    WHERE ((CUSTOMER_CD LIKE '2017%' AND MW_FLG = 'M') 
    OR (CUSTOMER_CD LIKE '2019%' AND MW_FLG = 'W')) 
    AND TOTAL_POINT <= 30000
    ORDER BY TOTAL_POINT ASC;

--IN
SELECT * FROM TB_CUSTOMER
    WHERE CUSTOMER_CD IN ('2017108' , '2018254' , '2019167')
    AND MW_FLG = 'M';
    
SELECT ITEM_CD, ITEM_NM FROM TB_ITEM_INFO
    WHERE ITEM_CD IN ('S01' , 'S04' , 'S06' , 'S10');
    
SELECT CUSTOMER_CD, SEQ_NO, POINT_MEMO, POINT, REG_DTTM FROM TB_POINT
    WHERE CUSTOMER_CD IN ('2017042' , '2018087' , '2019095')
    AND POINT_MEMO LIKE '%구매%';
    
--ORDER BY

SELECT CUSTOMER_CD, SEQ_NO, POINT_MEMO, POINT, REG_DTTM FROM TB_POINT
    WHERE REG_DTTM LIKE '2019%' AND POINT_MEMO LIKE '%구매%'
    ORDER BY POINT DESC;
    
SELECT * FROM TB_GRADE 
    WHERE CLASS_CD = 'B'
    ORDER BY KOR + ENG + MAT DESC;

